### ISSUE TITLE
XMLHttpRequest is not supported by your browser

### ISSUE THREAD

**Issue by ZloIzTabakerki** [Enngage/KenticoCloudDeliveryNodeSDK#1]
I have the same problem as for TypeScript SDK. 

`Error: XMLHttpRequest is not supported by your browser`

**Comment by Enngage** [comment]
This issue happens when you do HTTP request in an environment that does not support it. This means that if you run Typescript SDK in node.js, you would see this error. Though, this Node SDK should work just fine under node.js (but not in browser!). 

Anyway, this SDK will become obsolete. I'm working on a new version of Typescript SDK that supports both node.js and browser. Its published as beta version on npm under `4.0.0-beta.5` version.

There are some breaking changes so please refer to new documentation here -> https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/tree/major-version-node-js-support

**Comment by ZloIzTabakerki** [comment]
But I used Node SDK in node.js and got this error.

Also, when I used Typescript SDK beta, I've got another error: 
`TypeError: rxjs_1.bindCallback is not a function`

Even when I used Promises. And even when I downloaded rxjs package to my project. But, probably, this issue is for another repository :)

**Comment by Enngage** [comment]
Not sure about the first one - are you sure that its the node.js doing the requests?

`TypeError: rxjs_1.bindCallback is not a function`

Is almost certainly caused by an old version of `rxjs`. The `rxjs` team is currently refactoring the library and they haven't yet published the 6th version as latest on npm. Can you change the rxjs version to `6.0.0-rc.0` and install it? I hope this one helps :-) Let me know how it works.

**Comment by ZloIzTabakerki** [comment]
It was definetly node.js (9.11.1) :) I executed example code from repo directly in node.js without any additional code.

rxjs6 helped. Thanks, now it works :)

**Comment by Enngage** [comment]
Awesome, happy to hear that :) 

I don't know about this Node SDK, but it will become obsolete very soon anyway in favor of the aforementioned SDK.
